# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insert_table_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/insert_table.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        self.label.setMinimumSize(QtCore.QSize(0, 27))
        self.label.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.rows_spinbox = QtWidgets.QSpinBox(self.splitter)
        self.rows_spinbox.setObjectName("rows_spinbox")
        self.verticalLayout.addWidget(self.splitter)
        self.splitter_2 = QtWidgets.QSplitter(Dialog)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(self.splitter_2)
        self.label_2.setMinimumSize(QtCore.QSize(0, 27))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.columns_spinbox = QtWidgets.QSpinBox(self.splitter_2)
        self.columns_spinbox.setObjectName("columns_spinbox")
        self.verticalLayout.addWidget(self.splitter_2)
        self.splitter_3 = QtWidgets.QSplitter(Dialog)
        self.splitter_3.setMinimumSize(QtCore.QSize(0, 27))
        self.splitter_3.setMaximumSize(QtCore.QSize(16777215, 27))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_3 = QtWidgets.QLabel(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.border_style_comboBox = QtWidgets.QComboBox(self.splitter_3)
        self.border_style_comboBox.setMinimumSize(QtCore.QSize(0, 27))
        self.border_style_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.border_style_comboBox.setFont(font)
        self.border_style_comboBox.setCurrentText("")
        self.border_style_comboBox.setObjectName("border_style_comboBox")
        self.verticalLayout.addWidget(self.splitter_3)
        self.splitter_4 = QtWidgets.QSplitter(Dialog)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.label_4 = QtWidgets.QLabel(self.splitter_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.layout_directio_comboBox = QtWidgets.QComboBox(self.splitter_4)
        self.layout_directio_comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.layout_directio_comboBox.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.layout_directio_comboBox.setFont(font)
        self.layout_directio_comboBox.setObjectName("layout_directio_comboBox")
        self.verticalLayout.addWidget(self.splitter_4)
        self.insert_table_dialog = QtWidgets.QDialogButtonBox(Dialog)
        self.insert_table_dialog.setOrientation(QtCore.Qt.Horizontal)
        self.insert_table_dialog.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.insert_table_dialog.setObjectName("insert_table_dialog")
        self.verticalLayout.addWidget(self.insert_table_dialog)

        self.retranslateUi(Dialog)
        self.insert_table_dialog.accepted.connect(Dialog.accept)
        self.insert_table_dialog.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Number of Rows"))
        self.label_2.setText(_translate("Dialog", "Number of Columns"))
        self.label_3.setText(_translate("Dialog", "Border Style"))
        self.label_4.setText(_translate("Dialog", "Layout Direction"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
